  CLIENT_ID="253723893500-bihee0nbk4rknss8t5fjq1qeclpsu6ba.apps.googleusercontent.com"
  CLIENT_SECRET="jldzjGD672iWHxc_-B8nDWGH"
  REFRESH_TOKEN="1/cyZnOOdEGluUEHZb7P4mz_65euzfH89lCJhKNikIppI"
  ACCESS_TOKEN ="ya29.Glv-BTtBEFTrbAC6M2fe_oOWHuPFSR84HU6996MBUV56Mw_oB_DeQishuinHmsbj5Jk44v0cQmIm1NYtUCt55zyq_TJTgSCncQ42-YlolxWqB6HUIb0N8BZAAQfj"
  SENDER="kasundanthaa@gmail.com"
  RECIPIENT="kasunbandaraa@gmail.com"
  USER_ID="me"
  SUBJECT= "Email-Subject"
  MESSAGEBODY="Email Message Body Text 12345 test"
  CONTENTTYPE="gmail:TEXT_PLAIN"
  LABELID="Label_3394238941988420965"

	  
